$schema: http://json-schema.org/draft-07/schema#
$id: urn:mef:xid:spec:legato:ip-performance-monitoring-configuration:v0.0.2:all
x-mef-target: ServiceSpecificConfiguration
description: IP Performance Monitoring Configuration Schema.
title: 
    MEF LSO Legato - IP Performance Monitoring Configuration
    # MEF Forum - Date: 20241220  Edit-level: 
    # File: ip/faultAndPerformanceManagement/ipPerformanceMonitoringConfiguration.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # Â© MEF Forum 2024. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
type: object
properties:
  description: >-
    Data type representing the IP packet performance statistics configuration for receive and transmit. 
  protocol:
    description: Protocol type
    type: string
    enum:
      - IPV4
      - IPV6
      - ARP
  packetsIn:
    description: Enable or disable collection of input IP packets on monitored interface.
    type: boolean
  charsIn:
    description: Enable or disable collection of input IP characters on monitored interface.
    type: boolean
  packetsOut:
    description: Enable or disable collection of output IP packets on monitored interface.
    type: boolean
  charsOut:
    description: Enable or disable collection of output IP characters on monitored interface.
    type: boolean
  utilizationIn:
    description: Enable or disable collection of input bandwdith utilization on monitored interface.
    type: boolean
  utilizationOut:
    description: Enable or disable collection of output bandwdith utilization on monitored interface.
    type: boolean
  peakUtilizationIn:
    description: Enable or disable collection of input peak bandwdith utilization on monitored interface.
    type: boolean
  peakUtilizationOut:
    description: Enable or disable collection of output peak bandwdith utilization on monitored interface.
    type: boolean