$schema: http://json-schema.org/draft-07/schema#
$id: urn:mef:lso:spec:legato:ip-fault-management-configuration:v0.0.1:all
x-mef-target: ServicePayloadSpecificAttributes
description: IP Fault Management Configuration Schema.
title: 
    MEF LSO Legato - IP Fault Management Configuration
    # MEF Forum - Date: 20230627  Edit-level: 
    # File: ip/faultAndPerformanceManagement/ipFaultManagementConfiguration.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # Â© MEF Forum 2023. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
type: object
properties:
  description: >-
      The IP Fault Management configuration includes 
  properties:
    entity:
      $ref: '#/components/schemas/Entity'
    vlan:
      type: integer
    startTime:
      format: date-time
      type: string
    endTime:
      format: date-time
      type: string
    Entity:
      description: Data type representing an interface, VLAN, End Point, etc.
      properties:
        entityType: 
          oneOf:
            - $ref: '#/components/schemas/SlsReferencePoint'
            - $ref: '#/components/schemas/IpvcEndPoint'
            - $ref: '#/components/schemas/Location'
            - $ref: '#/components/schemas/Interface'
      type: object
    Interface:
      description: Data type representing an interface on a physical or logical device.
      properties:
        interface: 
          description: Interface identifier.
          type: string
          maxLength: 53
          pattern: "[\x20-\x7F]+"
    IpvcEndPoint:
      description: A subclass of a SlsReferencePoint.
      properties:
        id:
          description: IPVC End Point unique identifier
          type: string
        description:
          description: IPVC End Point description
          type: string
      type: object
    Location:
      allOf:
        - $ref: '#/components/schemas/SlsReferencePoint'
        - description: A subclass of a SlsReferencePoint.
          properties:
            ipvcEndpoint:
              description: Pointer to IPVC End Point
              items:
                type: string
              type: array
            name:
              description: Location name
              type: string
            description:
              description: Location description
              type: string
            cloudService:
              description: Attribute to indicate if associated with a cloud service.
              type: boolean
          type: object
      type: object
    SlsReferencePoint:
      oneOf:
        - $ref: '#/components/schemas/Location'
        - $ref: '#/components/schemas/IpvcEndPoint'
        - description: SlsReferencePoint is an abstract data type that can be subclassed to IpvcEndPoint and Location. Reference MEF 61.1 Section 10.9.1 SLS Reference Points.
          type: object
    SlsRpPair:
      description: Service Level Specification Reference Point Pair. In a multipoint or rooted multipoint IPVC, performance objectives are ideally specified as applying between pairs of IPVC EPs - in other words, they apply to the performance that IP Data Packets experience as they flow from one EI to another. The SlsRpPair is a representation of this association. Reference MEF 61.1 Section 10.9.1
      properties:
        fromSlsReferencePoint:
          $ref: '#/components/schemas/SlsReferencePoint'
        toSlsReferencePoint:
          $ref: '#/components/schemas/SlsReferencePoint'
      type: object
    TimeDuration:
      description: This class is used to describe durations expressed as a 2-tuple, (value, units). The units from from nanoseconds to years.
      properties:
        timeDurationValue:
          description: The value of the duration. For example, if the duration is 20 ms, this element is 20.
          type: integer
        timeDurationUnits:
          $ref: '#/components/schemas/TimeDurationUnits'
      type: object
    TimeDurationUnits:
      description: |-
        The unit of measure in the duration. For example, if an interval is 2ms, this element is MS.
      enum:
        - NS
        - US
        - MS
        - SEC
        - MIN
        - HOUR
        - DAY
        - WEEK
        - MONTH
        - YEAR
      type: string
    TimePeriod:
      description: A period of time, either as a deadline (endDateTime only) a startDateTime only, or both
      properties:
        startDateTime:
          description: Start of the time period, using IETC-RFC-3339 format
          example: '1985-04-12T23:20:50.520Z'
          format: date-time
          type: string
        endDateTime:
          description: End of the time period, using IETC-RFC-3339 format
          example: '1985-04-12T23:20:50.520Z'
          format: date-time
          type: string
      type: object